name: Проверка файлов
on: [push, pull_request]
permissions:
  contents: read
jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sh tools/check_files.sh
